/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidad1;

import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author jesuseduardo
 */
public class temperaturas extends javax.swing.JFrame {

    /**
     * Creates new form temperaturas
     */
    public temperaturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        lblEtiqueta1 = new javax.swing.JLabel();
        lblEtiqueta3 = new javax.swing.JLabel();
        lblEtiqueta4 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtCentigrados = new javax.swing.JTextField();
        txtFarenheit = new javax.swing.JTextField();
        btnCentigrados = new javax.swing.JButton();
        btnFarenheit = new javax.swing.JButton();
        btnfecha = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CONVERCION DE TEMPERATURAS");
        setBackground(java.awt.SystemColor.windowBorder);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(51, 51, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblEtiqueta1.setText("Conversor de Temperaturas");

        lblEtiqueta3.setBackground(new java.awt.Color(255, 255, 0));
        lblEtiqueta3.setText("  Grados centigrados:");
        lblEtiqueta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        lblEtiqueta4.setBackground(new java.awt.Color(255, 255, 51));
        lblEtiqueta4.setText("Grados farenheit");
        lblEtiqueta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        lblFecha.setBackground(new java.awt.Color(0, 255, 204));
        lblFecha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblFechaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtCentigrados.setEditable(false);
        txtCentigrados.setBackground(new java.awt.Color(102, 255, 51));
        txtCentigrados.setForeground(new java.awt.Color(153, 0, 153));
        txtCentigrados.setText("0.0");
        txtCentigrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCentigradosActionPerformed(evt);
            }
        });

        txtFarenheit.setEditable(false);
        txtFarenheit.setBackground(new java.awt.Color(102, 255, 102));
        txtFarenheit.setText("32.0");
        txtFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFarenheitActionPerformed(evt);
            }
        });

        btnCentigrados.setBackground(new java.awt.Color(153, 255, 102));
        btnCentigrados.setText("+1");
        btnCentigrados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 153, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(102, 0, 255)));
        btnCentigrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentigradosActionPerformed(evt);
            }
        });

        btnFarenheit.setBackground(new java.awt.Color(153, 255, 153));
        btnFarenheit.setText("+1");
        btnFarenheit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        btnFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarenheitActionPerformed(evt);
            }
        });

        btnfecha.setText("Haz Click Aqui...");
        btnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEtiqueta3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(lblEtiqueta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFarenheit, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtCentigrados))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFarenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCentigrados, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblEtiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnfecha)
                        .addGap(42, 42, 42)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEtiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfecha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEtiqueta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCentigrados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCentigrados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFarenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFarenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEtiqueta4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCentigradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCentigradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCentigradosActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnCentigradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentigradosActionPerformed
        // TODO add your handling code here:
        double TempCentigrados;
        TempCentigrados = Double.parseDouble(txtCentigrados.getText());
         TempCentigrados = TempCentigrados +1;
         txtCentigrados.setText( String.valueOf (TempCentigrados));
         double TempFarenheit ;
         TempFarenheit = TempCentigrados * (9/5)+32;
         txtFarenheit.setText(String.valueOf(TempFarenheit));
    }//GEN-LAST:event_btnCentigradosActionPerformed

    private void btnFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarenheitActionPerformed
        // TODO add your handling code here:
        double TempFarenheit;
        TempFarenheit= Double.parseDouble(txtFarenheit.getText());
        TempFarenheit = TempFarenheit+1;
        txtFarenheit.setText(String.valueOf(TempFarenheit));
        double TempCentigrados;
        TempCentigrados = TempFarenheit -32;
        txtCentigrados.setText(String.valueOf(TempCentigrados));
    }//GEN-LAST:event_btnFarenheitActionPerformed

    private void txtFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFarenheitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFarenheitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resultado;
        resultado = JOptionPane.showConfirmDialog(null, "Deseas Salir?");
        if (resultado == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        else
        {
            
        }
    }//GEN-LAST:event_formWindowClosing

    private void lblFechaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblFechaAncestorAdded
        // TODO add your handling code here:
    ;
    }//GEN-LAST:event_lblFechaAncestorAdded

    private void btnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfechaActionPerformed
        // TODO add your handling code here:
        Calendar Cal = Calendar.getInstance();
        String fec = Cal.get(Cal.DATE)+ " / " +(Cal.get(Cal.MONTH)+1)+ " / " +Cal.get(Cal.YEAR);
     //   int mes =(Cal.getFirstDayOfWeek());
        //int año = Cal.get(Cal.YEAR);
lblFecha.setText("La Fecha es " + fec );//+  " de "  + mes +  " del año " + año );
    }//GEN-LAST:event_btnfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(temperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(temperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(temperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(temperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new temperaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentigrados;
    private javax.swing.JButton btnFarenheit;
    private javax.swing.JButton btnfecha;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel lblEtiqueta1;
    private javax.swing.JLabel lblEtiqueta3;
    private javax.swing.JLabel lblEtiqueta4;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTextField txtCentigrados;
    private javax.swing.JTextField txtFarenheit;
    // End of variables declaration//GEN-END:variables
}
